# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woonplaats', models.CharField(max_length=50)),
                ('straatnaam', models.CharField(blank=True, max_length=50)),
                ('huisnummer', models.CharField(blank=True, max_length=10)),
                ('postbus', models.BooleanField(default=False)),
                ('postbusnummer', models.CharField(blank=True, max_length=10)),
                ('postcode', models.CharField(max_length=7)),
                ('land', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gebruiker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.IntegerField(choices=[('0', 'Normaal'), ('1', 'Vereniging')], null=True)),
                ('adres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vereniging.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='ZeilVereniging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default='')),
                ('bezoekadres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bezoekadres', to='vereniging.Adres', verbose_name='Bezoek adres')),
                ('postadres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postadres', to='vereniging.Adres', verbose_name='Post adres')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='zeilvereniging',
            order_with_respect_to='naam',
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='vereniging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vereniging.ZeilVereniging'),
        ),
    ]
