# Generated by Django 2.1.5 on 2019-02-02 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vereniging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruiker',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gebruiker',
            name='vereniging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vereniging.ZeilVereniging'),
        ),
        migrations.AlterField(
            model_name='gebruikersadres',
            name='gebruiker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vereniging.Gebruiker'),
        ),
        migrations.AlterField(
            model_name='verenigingsadres',
            name='vereniging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vereniging.ZeilVereniging'),
        ),
    ]
