# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vereniging', '0002_auto_20160430_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zeilvereniging',
            options={'verbose_name': 'Zeil vereniging', 'verbose_name_plural': 'Zeil verenigingen'},
        ),
        migrations.AlterField(
            model_name='zeilvereniging',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
